defaults:
  - _self_
  - method: mamba
  - env: sim

frame_skips: 1
condition_dropout: 0.5
condition_guidance_w: 1.2

clip_denoised: true
discount: 0.99
hidden_dim: 1024

## training
n_epochs: 100000
loss_type: l2
n_train_steps: 1e9
batch_size: 128
learning_rate: 5e-5
gradient_accumulate_every: 1
ema_decay: 0.995
log: false
log_freq: 1000
save_freq: 10000
log_dir: 'logs/'
project_name: HDP
run_name: ''

load_model_path: ''
online_eval: false
headless: true 

mamba_var: multi
action_mode: mamba
online_eval_start: 20000

mamba_optim: false
mamba_optim_steps: 0
mamba_lr: 10
eval_only: false

pose_augment: false
use_cached: true
ds_img_size: 128
